### ISSUE TITLE
Is it possible to generate JS file?

### ISSUE THREAD

**Issue by guoyunhe** [svg-sprite/gulp-svg-sprite#106]
In my project, I want to load SVG sprite in JS:

```js
// sprite.js
module.exports = `<svg>...</svg>`;
```

Is it possible to add this feature?

Thanks!

**Comment by zhangchenglin** [comment]
What is the use of this?
Is it practical?

**Comment by XhmikosR** [comment]
You could use Node fs to read the file and use it as string.
