### ISSUE TITLE
Denial of Service  - Vulnerabilities Observed in dependent package

### ISSUE THREAD

**Issue by deepakb2410** [svg-sprite/gulp-svg-sprite#114]
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ css-what                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-svg-sprite [dev]                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-svg-sprite > svg-sprite > svgo > css-select > css-what  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1754                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by XhmikosR** [comment]
Nothing we can do here. I have updated svgo in svg-sprite's main branch but there are still some issues so I can't cut a new major release.
