### ISSUE TITLE
Considering using resvg-js instead of svg2png?

### ISSUE THREAD

**Issue by yisibl** [svg-sprite/gulp-svg-sprite#119]
Have you considered using [resvg-js](https://github.com/yisibl/resvg-js) instead of svg2png? resvg-js is almost the fastest and most compatible SVG library.

In some scenarios,`resvg-js` is even faster than sharp.

## Benchmark

```shell
Running "resize width" suite...
  resvg-js(Rust):
    12 ops/s, ±22.66%   | fastest 🚀

  sharp:
    9 ops/s, ±64.52%    | 25% slower

  skr-canvas(Rust):
    7 ops/s, ±3.72%    | 41.67% slower

  svg2img(canvg and node-canvas):
    6 ops/s, ±16.94%    | slowest, 50% slower
```

![image](https://user-images.githubusercontent.com/2784308/138337267-6c33449f-8f89-49c8-a387-2338ffd79b6a.png)

See also https://github.com/RazrFalcon/resvg#svg-support

**Comment by XhmikosR** [comment]
svg2png is a devDependency so I personally don't worry much about it. Also, upstream, we need to remove phantomjs and that PR gets rids of svg2png upstream. Here, I wouldn't mind using a solution that's used upstream and works fine cross platform.

Also, do note that I don't have the bandwidth to maintain everything myself. I just pushed some recent patches here to update some stuff with the hopes that we'll be able to release svg-sprite v2.0.0 upstream.

**Comment by yisibl** [comment]
Great, upstream has been migrated to resvg-js: https://github.com/svg-sprite/svg-sprite/pull/554

**Comment by XhmikosR** [comment]
Closing this since it's related to upstream.
