### ISSUE TITLE
Release 1.5.1 (arm64 issues)

### ISSUE THREAD

**Issue by patrykbura** [svg-sprite/gulp-svg-sprite#127]
Hey, do you plan release of changes from `dev` branch anytime soon?

I'm working on amr64 CPU, and dropping PhantomJS in https://github.com/svg-sprite/svg-sprite/releases/tag/v2.0.0-beta1 which causes problems with installation helps alot.

Thanks!

**Comment by Didel** [comment]
For my use case (M1 MacBook) I was able to successfully switch to https://github.com/wesoledi/gulp-svg-sprite . It is a bit behind (currently uses 2.0.0-beta2 instead of the latest beta4, but was able to successfully build and install and generate my SVG sprites.

**Comment by Kreeg** [comment]
I would say that this will happen within the month
