### ISSUE TITLE
SonarCloud is complaining about security hotspot in icons.html

### ISSUE THREAD

**Issue by banoodle** [svg-sprite/gulp-svg-sprite#129]
We just started using sonarcloud to run static code tests on our git commits.

It is complaining that the hyperlink inside the generated icons.html lacks a rel=noopener attribute which it considers a security hotspot.

Could this attribute be added to the next release? I notice this has been fixed in the svg-sprite repo.

![Screen Shot 2022-06-01 at 2 04 16 PM](https://user-images.githubusercontent.com/7685811/171503440-a55e15cc-027a-4352-b550-cb8f318598cc.png)

**Comment by Kreeg** [comment]
Hi! This is already fixed in svg-sprite package. And will be fixed here in the next release this month.
