### ISSUE TITLE
When are you planning to release this as npm package? The npm package was last published 4 years ago and there seems to be a new update here. I am facing some issue with PhantomJS dependency on Apple M1 and seems like the new github code can solve it.

### ISSUE THREAD

**Issue by arijitpatrainstafreight** [svg-sprite/gulp-svg-sprite#132]
The npm package was last published 4 years ago and there seems to be a new update here. I am facing some issue with PhantomJS dependency on Apple M1 and seems like the new GitHub code here can solve it. When are you planning to release this as npm package?

**Comment by Kreeg** [comment]
@arijitpatrainstafreight hello. The short answer is "soon". You can follow it here #130

**Comment by seahindeniz** [comment]
Hi @Kreeg, may I know why this issue got closed? 
Seems like related PR hasn't got merged yet

**Comment by Kreeg** [comment]
Hi @seahindeniz. It's merged and 2.0 version has been released

**Comment by arijitpatrainstafreight** [comment]
thank you... wohoo!
