### ISSUE TITLE
Inconsistent xmlns attributes in each def

### ISSUE THREAD

**Issue by benjarwar** [svg-sprite/gulp-svg-sprite#70]
I'm compiling a sprite and checking the file into my repo. But I'm getting inconsistent results. Sometimes, the `xmlns` attribute is added to each embedded `<svg>`, sometimes it is not. This is causing minor inconvenience, as it causes diffs in our pull requests when there aren't actual changes.

I've referenced [what you wrote here about the inline setting](https://github.com/jkphl/svg-sprite/issues/205#issuecomment-263670414) and tried adding `inline: false` to my config, but it doesn't seem to solve the problem.

Here's my pipe:

```
.pipe(svgSprite({
  mode: {
    defs: {
      dest: '.',
      prefix: '',
      sprite: 'sprite.svg'
    }
  },
  svg: {
    dimensionAttributes: false
  },
}))
```

Thanks in advance!

**Comment by jkphl** [comment]
@benjarwar I've got no explanation why it should give you inconsistent results, unfortunately, and I never experienced something similar. Could you please send me the source SVGs you're working with as well as tell me your Node / Gulp versions so I can try to reproduce it?

**Comment by jkphl** [comment]
@benjarwar Thanks! Yeah, some sample SVGs (in the same style as used for the client project) would probably help to reproduce this. :)

**Comment by benjarwar** [comment]
Can you tell me which is the expected behavior, given my config without an `inline` value? Should the nested `<svg>` elements have `xmlns` attributes, or no?

**Comment by jkphl** [comment]
@benjarwar Hard to say off the top of my head (and I don't exactly remember), it might depend on the input SVG. In any case, namespace declarations should be spripped when `inline: true`.

**Comment by benjarwar** [comment]
Setting `inline: true` seems to only affect the root level `<svg>` element. The nested elements still have `xmlns` attributes (and it's in the nested elements that I've seen inconsistencies).

**Comment by zslabs** [comment]
Also experiencing this in https://github.com/rhinogram/rhinostyle if you pull-down, install deps, and run `gulp icons`

**Comment by zslabs** [comment]
@jkphl ☝️ That repo I linked to is a good example of source SVGs and what's being built. You can find the built icons in https://github.com/rhinogram/rhinostyle/blob/master/build/svg/sprite.svg

**Comment by afogelberg** [comment]
I'm also experiencing problems with xmlns attribute added to each symbol, if I use version 1.3.7. However if I use the 1.2.14 version, as also [material-design-icons](https://github.com/google/material-design-icons/blob/master/package.json) use, the problem disappears.

**Comment by jkphl** [comment]
I didn't dig deeper into this so far, but I think this might be some SVGO plugin and its default behaviour. Maybe have a look at the [removeXMLNS](https://github.com/svg/svgo/blob/master/plugins/removeXMLNS.js), [removeEditorsNSData](https://github.com/svg/svgo/blob/master/plugins/removeEditorsNSData.js) or [removeUnusedNS](https://github.com/svg/svgo/blob/master/plugins/removeUnusedNS.js) plugin and disable it (see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#custom-shape-transformations-object-values) for documentation).

**Comment by benjarwar** [comment]
@Kreeg no, but only because I haven't been using this library since 2017. 😅

**Comment by Kreeg** [comment]
Ok, feel free to create a new issue. A lot of changes have been done since 2017 :)
