### ISSUE TITLE
Can't seem to get it working

### ISSUE THREAD

**Issue by mearleycf** [svg-sprite/gulp-svg-sprite#76]
Here's the gulp file.js: 
```
// gulp-svg-sprite
svgSprite = require('gulp-svg-sprite');
let spriteConfig = {
  mode: {
    css: {
      render: {
        css: true
      }
    }
  }
};
gulp.task('sprites', function () {
  return gulp.src('**/.*.svg', {cwd: 'source/images'})
    .pipe(svgSprite(spriteConfig))
    .pipe(gulp.dest('source/test'));
});

// end gulp-svg-sprite
```
the directory is
+ foo
--source
----images
--gulpfile.js

Obviously there are more folders than that, but this is all that's relevant to now. 

I've tried doing `./source/images'` as well and that does not work either.

**Comment by Kreeg** [comment]
@mearleycf Hello! I'm closing it due to inactivity. If you still have this problem please open a new issue. Thanks
