### ISSUE TITLE
cant remove <style> from my compiled sprite.svg

### ISSUE THREAD

**Issue by NickolasDzR** [svg-sprite/gulp-svg-sprite#93]
my compiled file sprites.svg adds properties like
"<styles>:root>svg{display:none}:root>svg:target{display:block}<styles>"
svg{display:none} is why i cant use my sprites, they just dont show up when i add in my pug. And i tryed many of way to fix it but i couldn't

can you say what is it and if you have any way to fix it i will glad.

**Comment by XhmikosR** [comment]
That's unrelated to gulp-svg-sprite, you should check the upstream issues.

**Comment by cssfish** [comment]
see [https://github.com/svg-sprite/gulp-svg-sprite/issues/66]
